# Generated by Django 3.1.1 on 2020-09-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='perfil_investidor',
            field=models.CharField(max_length=48, null=True, verbose_name='Perfil de Investidor'),
        ),
    ]
