# Generated by Django 3.1.1 on 2020-09-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safira', '0002_cliente_perfil_investidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=models.FloatField(null=True, verbose_name='Limite de Crédito'),
        ),
    ]
